name: Build and test project on linux

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  ubuntu-build-clang:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: cmake clang ninja-build
    - run: cmake -B ${{github.workspace}}/build -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja
    - run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target check

  nix-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build
    - run: nix flake check